export const images = {
  balls: require('./balls.jpeg'),
  deer: require('./deer.jpeg'),
  diamond: require('./diamond.jpeg'),
  library: require('./library.jpg'),
  platform: require('./platform.jpeg'),
  altar: require('./altar.jpeg'),
  angel: require('./angel.jpeg'),
  boo: require('./boo.jpeg'),
  donut: require('./donut.jpeg'),
  girl: require('./girl.jpeg'),
  globe: require('./globe.jpeg'),
  lines: require('./lines.jpeg'),
  planet: require('./planet.jpeg'),
  splines: require('./splines.jpeg'),
  // vase: require('./vase.jpeg'),
};